Project_Timer.xcodeproj/project.pbxproj, Project_Timer/Global/Extension/Notification+Extension.swift, Project_Timer/Global/Extension/String+Extension.swift, Project_Timer/Network/DTO/AppstoreVersion.swift, Project_Timer/Network/Network.swift, Project_Timer/Network/NetworkController.swift, Project_Timer/Network/NetworkProtocols.swift, Project_Timer/Network/NetworkStatus.swift, Project_Timer/Network/NetworkURL.swift, Project_Timer/SceneDelegate.swift, Project_Timer/Stopwatch/StopwatchViewController.swift, Project_Timer/Timer/TimerViewController.swift, Project_Timer/en.lproj/Localizable.strings, Project_Timer/ko.lproj/Localizable.strings
=> 업데이트 팝업로직 및 아이패드 화면회전로직 비활성화

Project_Timer.xcodeproj/project.pbxproj, Project_Timer/Global/Extension/Notification+Extension.swift, Project_Timer/Global/Extension/String+Extension.swift, Project_Timer/Network/DTO/AppstoreVersion.swift, Project_Timer/Network/Network.swift, Project_Timer/Network/NetworkController.swift, Project_Timer/Network/NetworkProtocols.swift, Project_Timer/Network/NetworkStatus.swift, Project_Timer/Network/NetworkURL.swift, Project_Timer/SceneDelegate.swift, Project_Timer/Stopwatch/StopwatchViewController.swift, Project_Timer/Timer/TimerViewController.swift, Project_Timer/en.lproj/Localizable.strings, Project_Timer/ko.lproj/Localizable.strings
아이패드 사용자의 화면전환 로직을 수정하였습니다.
새 버전 업데이트 팝업로직을 추가하였습니다.
Modified : The rotation algorithm of iPad users.
New : pop-up alert for update new version
=> [Publish] ver 6.5.1

Project_Timer.xcodeproj/project.pbxproj, Project_Timer/Base.lproj/Main.storyboard, Project_Timer/Global/Extension/Notification+Extension.swift, Project_Timer/Global/Extension/UIViewController+Extension.swift, Project_Timer/Stopwatch/SetTimerViewController2.swift, Project_Timer/Stopwatch/StopwatchVM.swift, Project_Timer/Stopwatch/StopwatchViewController.swift, Project_Timer/Timer/SetViewController.swift, Project_Timer/Timer/TimerVM.swift, Project_Timer/Timer/TimerViewController.swift, Project_Timer/en.lproj/Localizable.strings, Project_Timer/ko.lproj/Localizable.strings, README.md
=> 기록날짜 확인 기능 추가

Project_Timer.xcodeproj/project.pbxproj, Project_Timer/Base.lproj/Main.storyboard, Project_Timer/Global/Extension/Notification+Extension.swift, Project_Timer/Global/Extension/UIViewController+Extension.swift, Project_Timer/Stopwatch/SetTimerViewController2.swift, Project_Timer/Stopwatch/StopwatchVM.swift, Project_Timer/Stopwatch/StopwatchViewController.swift, Project_Timer/Timer/SetViewController.swift, Project_Timer/Timer/TimerVM.swift, Project_Timer/Timer/TimerViewController.swift, Project_Timer/en.lproj/Localizable.strings, Project_Timer/ko.lproj/Localizable.strings, README.md
기록날짜 확인을 위한 기능이 추가되었습니다
new: checking date of recording
=> [Publish] ver 6.5.2

Project_Timer.xcodeproj/project.pbxproj, Project_Timer/Global/Model/RecordTimes.swift, Project_Timer/Global/UserDefaultsManager.swift, Project_Timer/Setting/Main/SettingCell.swift, Project_Timer/Setting/Main/SettingVM.swift, Project_Timer/Setting/Main/SettingViewController.swift, Project_Timer/Setting/SettingFunctionsList/SettingFunctionsListVC.swift, Project_Timer/Setting/SettingTiTiLab/SettingTiTiLabVC.swift, Project_Timer/Timer/ViewModel/TimerVM.swift, Project_Timer/en.lproj/Localizable.strings, Project_Timer/ko.lproj/Localizable.strings
=> Setting UI 사이즈조절 대응 및 Timer Notification 분리

Project_Timer.xcodeproj/project.pbxproj, Project_Timer/Global/Model/RecordTimes.swift, Project_Timer/Global/UserDefaultsManager.swift, Project_Timer/Setting/Main/SettingCell.swift, Project_Timer/Setting/Main/SettingVM.swift, Project_Timer/Setting/Main/SettingViewController.swift, Project_Timer/Setting/SettingFunctionsList/SettingFunctionsListVC.swift, Project_Timer/Setting/SettingTiTiLab/SettingTiTiLabVC.swift, Project_Timer/Timer/ViewModel/TimerVM.swift, Project_Timer/en.lproj/Localizable.strings, Project_Timer/ko.lproj/Localizable.strings
기록수정 저장 관련 버그 수정
Timer 알림을 분리 및 Setting창 UI 크기조절 대응
Bug Fixed: saving edited record
Separate Timer notifications and modify Setting UI for adjust window size
=> [Publish] ver 7.4.1

Project_Timer.xcodeproj/project.pbxproj, Project_Timer/Timer/ViewModel/TimerVM.swift
Bug fixed: Timer 기록저장로직 버그 수정
Bug fixed: Timer stop & save logic
=> [Hotfix] timer background 시간저장로직 버그 수정, 7.5.1 배포

Project_Timer.xcodeproj/project.pbxproj, Project_Timer/Logs/LogHome/SwiftUI/Model/WeekSmallTime.swift, Project_Timer/Stopwatch/StopwatchViewController.swift, Project_Timer/Timer/TimerViewController.swift
=> Week 기록구간 버그 수정

Project_Timer.xcodeproj/project.pbxproj, Project_Timer/Logs/LogHome/SwiftUI/Model/WeekSmallTime.swift, Project_Timer/Stopwatch/StopwatchViewController.swift, Project_Timer/Timer/TimerViewController.swift
Bug fixed: LogHome - Week 그래프 누적시간 오류 수정
Bug fixed: LogHome - Week graph's total time
=> [Publish] ver 7.7.1

Project_Timer.xcodeproj/project.pbxproj, Project_Timer/Global/Model/Daily.swift, Project_Timer/Global/Model/Storage.swift, Project_Timer/Logs/LogVC.swift, Project_Timer/Setting/Main/SettingCell.swift, Project_Timer/Setting/Main/SettingVM.swift, Project_Timer/Setting/Main/SettingViewController.swift, Project_Timer/en.lproj/Localizable.strings, Project_Timer/ko.lproj/Localizable.strings
=> EditHistory 로직 수정, JSON 파일 공유 추가

Project_Timer.xcodeproj/project.pbxproj, Project_Timer/Global/Model/Daily.swift, Project_Timer/Global/Model/Storage.swift, Project_Timer/Logs/LogVC.swift, Project_Timer/Setting/Main/SettingCell.swift, Project_Timer/Setting/Main/SettingVM.swift, Project_Timer/Setting/Main/SettingViewController.swift, Project_Timer/en.lproj/Localizable.strings, Project_Timer/ko.lproj/Localizable.strings
새로운 Backup 기능 추가 (JSON 파일 공유)
Bug fixed: 기록수정시 오후 ~ 오전 구간 오류 수정
New Backup feature has been added. (share JSON files)
Bug fixed: Edit Record (from PM ~ to AM)
=> [Publish] ver 7.8.1

Project_Timer/AppDelegate.swift, Project_Timer/Assets.xcassets/system_backgroup.colorset/Contents.json, Project_Timer/Assets.xcassets/system_backgroup2.colorset/Contents.json, Project_Timer/Base.lproj/Main.storyboard, Project_Timer/Global/Constant/TiTiColor.swift, Project_Timer/Global/Extension/Date+Extension.swift, Project_Timer/Logs/Dailys/Cell/ProgressDailyTaskCell.xib, Project_Timer/Logs/Dailys/Cell/StandardDailyTaskCell.xib, Project_Timer/Logs/Dailys/Graph/StandardDailyGraphView.swift, Project_Timer/Logs/Dailys/Graph/TasksProgressDailyGraphView.swift, Project_Timer/Logs/Dailys/Graph/TimelineDailyGraphView.swift, Project_Timer/Logs/LogVC.swift, Project_Timer/Logs/ModifyRecord/ModifyRecordVC.swift, Project_Timer/Logs/Weeks/Cell/StandardWeekTaskCell.xib, Project_Timer/Logs/Weeks/Graph/StandardWeekGraphView.swift, Project_Timer/Setting/Main/SettingVM.swift, Project_Timer/TaskSelect/taskSelectViewController.swift
[DateFormat](https://goddaehee.tistory.com/282)
[detect Mac](https://www.hackingwithswift.com/example-code/catalyst/how-to-detect-your-ios-app-is-running-on-macos-catalyst)
=> Mac 관련 로직추가 및 DateFormatter 수정

Project_Timer.xcodeproj/project.pbxproj, Project_Timer/AppDelegate.swift, Project_Timer/Assets.xcassets/system_backgroup.colorset/Contents.json, Project_Timer/Assets.xcassets/system_backgroup2.colorset/Contents.json, Project_Timer/Base.lproj/Main.storyboard, Project_Timer/Global/Constant/TiTiColor.swift, Project_Timer/Global/Extension/Date+Extension.swift, Project_Timer/Global/Model/Dummy.swift, Project_Timer/Logs/Dailys/Cell/ProgressDailyTaskCell.xib, Project_Timer/Logs/Dailys/Cell/StandardDailyTaskCell.xib, Project_Timer/Logs/Dailys/DailysVC.swift, Project_Timer/Logs/Dailys/Graph/StandardDailyGraphView.swift, Project_Timer/Logs/Dailys/Graph/TasksProgressDailyGraphView.swift, Project_Timer/Logs/Dailys/Graph/TimelineDailyGraphView.swift, Project_Timer/Logs/LogHome/SwiftUI/DailyView.swift, Project_Timer/Logs/LogHome/SwiftUI/WeekView.swift, Project_Timer/Logs/LogVC.swift, Project_Timer/Logs/ModifyRecord/ModifyRecordVC.swift, Project_Timer/Logs/Weeks/Cell/StandardWeekTaskCell.xib, Project_Timer/Logs/Weeks/Graph/StandardWeekGraphView.swift, Project_Timer/Logs/Weeks/WeeksVC.swift, Project_Timer/Setting/Main/SettingVM.swift, Project_Timer/TaskSelect/taskSelectViewController.swift
bug fixed: DateFormatter
Mac 과 관련된 로직 및 디자인 일부 수정
bug fixed: year of DateFormatter
modified: logic and design associated with Mac
=> [Publish] ver 7.8.2

Project_Timer.xcodeproj/project.pbxproj, Project_Timer/AppDelegate.swift, Project_Timer/Base.lproj/Main.storyboard, Project_Timer/Global/Extension/Color+Extension.swift, Project_Timer/Global/Extension/Date+Extension.swift, Project_Timer/Global/Extension/Int+Extension.swift, Project_Timer/Global/Extension/UIScrollView+Extension.swift, Project_Timer/Global/Model/Daily.swift, Project_Timer/Global/UserDefaultsManager.swift, Project_Timer/Global/View/LeftButton.swift, Project_Timer/Global/View/RightButton.swift, Project_Timer/Logs/Dailys/DailysVC.swift, Project_Timer/Logs/Dailys/DailysVM.swift, Project_Timer/Logs/Dailys/Graph/TasksProgressDailyGraphView.swift, Project_Timer/Logs/Dailys/Graph/TimeTableDailyGraphView.swift, Project_Timer/Logs/Dailys/SwiftUI/TimeTableView.swift, Project_Timer/Logs/Dailys/SwiftUI/ViewModel/TimeTableVM.swift, Project_Timer/Logs/LogHome/LogHomeVC.swift, Project_Timer/Logs/ModifyRecord/ModifyRecordVC.swift, Project_Timer/Logs/ModifyRecord/ModifyRecordVM.swift, Project_Timer/Logs/Weeks/WeeksVC.swift, Project_Timer/TaskSelect/taskSelectViewController.swift, Project_Timer/Todolist/TodolistViewController.swift, Project_Timer/Usecase/IOUsecase.swift
| Dark | Light |
| -------- | -------- |
| <img src="https://i.imgur.com/LsMBHdi.jpg"> | <img src="https://i.imgur.com/Pkubucc.jpg"> |
| 1 | 2 | 3 |
| -------- | -------- | -------- |
| <img src="https://i.imgur.com/Ezw7cLJ.png"> | <img src="https://i.imgur.com/8PgUBQJ.png"> | <img src="https://i.imgur.com/0LLlwsj.png"> |
- 막대의 경우 origin(x, y), size (width, height) 값을 통해 24시간 * 6칸 내 잘 위치하는 식으로 구현을 하였다.
- offset 함수를 통해 원하는 위치에 표현할 수 있었다.
- 시간대가 다른 구간의 기록의 경우 막대를 쪼개서 만들어 표현하는 식으로 구현하였다.
- 표 디자인이 그래프 위에 표시되기 위해서 SwiftUI 내에서 순서상 마지막에 구현하는 식으로 하여 구현하였다.
- 표는 Divider 를 통해 구현하였다.
막대 구조체
```swift
struct TimeTableBlock : Identifiable {
let id: Int
let colorIndex: Int
let hour: Int // y
let startSeconds: Int // x
let interver: Int // width
}
```
SwiftUI body 코드
```swift
var body: some View { …
```
=> TimeTable 그래프 구현, Scroll button 추가

Project_Timer.xcodeproj/xcshareddata/xcschemes/Project_Timer (dev).xcscheme, Project_Timer/AppDelegate.swift, Project_Timer/Global/Infos.swift, Project_Timer/Global/SingletonClass/KeyChain.swift, Project_Timer/Info.plist, Project_Timer/Network/NetworkURL.swift
- Issue:  #97 
- background: 
- iOS17로 올라가면서 Network 요청시 ATS(App Transport Security) 문제가 발생하였다.
- 또한 bundle identifier가 다른 scheme별로 keyChain이 분리될 수 있도록 개선이 필요하였다.
---
```xml
<key>NSAppTransportSecurity</key>
<dict>
<key>NSAllowsArbitraryLoads</key>
<true/>
<key>NSExceptionDomains</key>
<dict>
<key>$(ServerURL)</key>
<dict>
<key>NSExceptionAllowsInsecureHTTPLoads</key>
<true/>
</dict>
</dict>
</dict>
```
- ATS를 통해 HTTP 통신으로 Server와 RestAPI 통신 구현
- KeyChain에서 Bundle identifier를 통해 kSecAttrService를 사용하여 KeyChain 분리 구현
- keyChain 에서 enum key 값들 및 save, get, update, delete 구현
- 블로그가 아닌 애플 공식문서를 토대로 key, value 정의를 토대로 문제해결 경험
- 다중 Bundle identifier로 빌드될 수 있는 프로젝트에서 KeyChain을 분리하여 사용할 수 있도록 개선한 경험
- [NSExceptionDomains](https://developer.apple.com/documentation/bundleresources/information_propert …
=> 로그인 문제 해결 (ATS, KeyChain 문제 해결)

Project_Timer.xcodeproj/project.pbxproj, Project_Timer/Assets.xcassets/LoginSignup/loginBackgroundColor.colorset/Contents.json, Project_Timer/Global/Extension/Foundation/CGSize+Extension.swift, Project_Timer/LoginSignup/LoginSelect/AppleLoginButton.swift, Project_Timer/LoginSignup/LoginSelect/EmailLoginButton.swift, Project_Timer/LoginSignup/LoginSelect/GoogleLoginButton.swift, Project_Timer/LoginSignup/LoginSelect/LoginSelectView.swift, Project_Timer/en.lproj/Localizable.strings, Project_Timer/ko.lproj/Localizable.strings
- Issue: #105  
- Tech Spec: [회원 관리 기능 개발](https://www.notion.so/timertiti/4cb5c74f656e4bf784cff130213fd086?pvs=4)
- Figma: [로그인 프로세스](https://www.figma.com/file/T8hsaAguFkPytBiNMOOw03/Develop?type=design&node-id=670-9559&mode=design)
---
=> Login화면 화면크기변화에 따른 UI조정 및 Localization 반영

Project_Timer.xcodeproj/project.pbxproj, Project_Timer/AppDelegate.swift, Project_Timer/Data/API/AppVersionAPI.swift, Project_Timer/Data/DTO/AppLatestVersionDTO.swift, Project_Timer/Data/Repository/AppLatestVersionRepository.swift, Project_Timer/Domain/Entity/AppLatestVersionInfo.swift, Project_Timer/Domain/Interface/AppLatestVersionRepositoryInterface.swift, Project_Timer/Domain/UseCase/GetLatestVersionUseCase.swift, Project_Timer/Global/Infos.swift, Project_Timer/Info.plist, Project_Timer/Network/DTO/Decodable/BooleanValue.swift, Project_Timer/Network/NetworkController.swift, Project_Timer/Network/NetworkURL.swift, Project_Timer/Present/Interface/GetLatestVersionUseCaseInterface.swift, Project_Timer/Setting/Main/SettingVM.swift
- Issue:  #123 
- Tech Spec: [회원 관리 기능 개발](https://timertiti.notion.site/4cb5c74f656e4bf784cff130213fd086?pvs=4)
- Figma: [로그인 프로세스](https://www.figma.com/file/T8hsaAguFkPytBiNMOOw03/Develop?type=design&node-id=670-9559&mode=design)
---
=> 앱 업데이트 강제성 분기처리 구현

Project_Timer.xcodeproj/project.pbxproj, Project_Timer.xcodeproj/xcshareddata/xcschemes/Project_Timer.xcscheme, Project_Timer/Base.lproj/Main.storyboard, Project_Timer/Global/Model/Daily.swift, Project_Timer/Logs/LogDaily/SwiftUI/TimeTableView.swift, Project_Timer/Logs/LogDaily/SwiftUI/ViewModel/TimeTableVM.swift, Project_Timer/Network/NetworkURL.swift, Project_Timer/Setting/Main/SettingVC.swift, Project_Timer/Setting/Main/SettingVM.swift, Project_Timer/Stopwatch/StopwatchVC.swift, Project_Timer/Timer/TimerVC.swift, Project_Timer/Todolist/TodolistVC.swift
=> Setting 최신버전 수신 복구, TimeTableGraph 크기가 벗어나는 문제 해결

Project_Timer.xcodeproj/project.pbxproj, Project_Timer/Core/Global/Preview/UIViewControllerPreview.swift, Project_Timer/Core/Global/Preview/UIViewPreview.swift, Project_Timer/Core/Localize/TLRen.swift, Project_Timer/Core/Localize/TLRkey.swift, Project_Timer/Core/Localize/TLRko.swift, Project_Timer/Core/Localize/TLRzh.swift, Project_Timer/Present/Setting/Service/SettingTiTiLab/TestServer/SignupSigninVC.swift
- Issue: #136  
- Tech Spec: [비밀번호 재설정](https://timertiti.notion.site/fd978915722944cbb68c79da03f0852e?pvs=4)
- Figma: [비밀번호 찾기](https://www.figma.com/file/PndUrtAqgOFWlMDeifALwn/Playground?type=design&node-id=416-152&mode=design)
---
| ko | Find Nicnkame | Contect |
| -------- | -------- | -------- |
| ![IMG_6551](https://github.com/TimerTiTi/TiTi_iOS/assets/65349445/a9f67984-9ff0-4901-8853-23e326b772eb) | ![IMG_6552](https://github.com/TimerTiTi/TiTi_iOS/assets/65349445/5ad90b2c-435f-4fb5-a504-06d13c706d83) | ![IMG_6553](https://github.com/TimerTiTi/TiTi_iOS/assets/65349445/0379b354-4106-4807-8e2d-2b8cdd4ad881) |
| en | Find Nicnkame | Contect |
| -------- | -------- | -------- |
| ![IMG_6554](https://github.com/TimerTiTi/TiTi_iOS/assets/65349445/2c707969-57de-44f0-ba51-6dedc7749d85) | …
=> Signin 화면 내 닉네임 찾기, 비밀번호 찾기, 문의하기 추가

Project_Timer.xcodeproj/project.pbxproj, Project_Timer/Core/Extension/UIKit/UIViewController+Extension.swift, Project_Timer/Core/Localize/TLRen.swift, Project_Timer/Core/Localize/TLRkey.swift, Project_Timer/Core/Localize/TLRko.swift, Project_Timer/Core/Localize/TLRzh.swift, Project_Timer/Present/Setting/Service/SettingTiTiLab/SettingTiTiLabVC.swift, Project_Timer/Present/Setting/Service/SettingTiTiLab/TestServer/SyncDailys/SyncDailysVC.swift
- Issue:  #142 
- Tech Spec: Tech Spec: [비밀번호 재설정](https://timertiti.notion.site/fd978915722944cbb68c79da03f0852e?pvs=4)
- Figma: [비밀번호 찾기](https://www.figma.com/file/PndUrtAqgOFWlMDeifALwn/Playground?type=design&node-id=416-152&mode=design)
---
---
=> 로그아웃 기능 추가

Project_Timer/Core/Global/SingletonClass/DailyManager.swift, Project_Timer/Widget/SharedCode/Storage.swift
- Issue:  https://github.com/TimerTiTi/TiTi_iOS/issues/171
- Tech Spec: 
- Figma: 
---
- Storage에 변경 사항이 있습니다
---
=> dailys.json 백업 시스템 구축
